baseURL = "https://www.scottyob.com/"
languageCode = "en-us"
title = "Scott O'Brien"
theme = "half-milk"
paginate = 4


[params]
  tagline = "Ramblings and resources of my online life"
  backgroundColor = "#fff"
  linkColor = "#ff7010"
